IAB207-project/website/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from werkzeug.security import generate_password_hash,check_password_hash

from .models import User
from .forms import LoginForm,RegisterForm
from flask_login import login_user, login_required,logout_user
from . import db


#create a blueprint
bp = Blueprint('auth', __name__)

# this is the hint for a login function
@bp.route('/login', methods=['GET', 'POST'])
def login(): #view function
    login_form = LoginForm()
    error=None
    if(login_form.validate_on_submit()==True):
        user_name = login_form.user_name.data
        password = login_form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        if u1 is None:
             error='User name is incorrect or does not exist'
        elif not check_password_hash(u1.password_hash, password): # takes the hash and password
            error='Incorrect password'
        if error is None:
            login_user(u1)
            flash("You have successfully logged in: " + user_name)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@bp.route('/register', methods=['GET', 'POST'])
def register(): #view function
    register = RegisterForm()
    if (register.validate_on_submit() == True):
            uname =register.user_name.data
            pwd = register.password.data
            email=register.email_id.data
            phone = register.phone_number.data
            address = register.address.data
            #check if a user exists
            u1 = User.query.filter_by(name=uname).first()
            if u1:
                flash('User name already exists, please login')
                return redirect(url_for('auth.login'))
            # don't store the password - create password hash
            pwd_hash = generate_password_hash(pwd)
            #create a new user and commit to database
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email, contact_num = phone, address=address)
            db.session.add(new_user)
            db.session.commit()
            # redirect to HTML page
            flash("You have successfully registered")
            return redirect(url_for('auth.login'))
    else:
        return render_template('user.html', form=register, heading='Register')
        
@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have successfully logged out")
    return redirect(url_for('/login'))


IAB207-project/website/views.py
from flask import Blueprint,render_template,url_for,redirect
from flask_login import current_user, login_required,logout_user
from .models import Event
from .forms import EventForm
bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    event = Event.query.all()    
    return render_template('index.html', event=event)

@bp.route('/search')
def search():
    if request.args['search']:
        print(request.args['search'])
        eve = "%" + request.args['search'] + '%'
        event = Event.query.filter(Event.description.like(eve)).all()
        return render_template('index.html', event=event)
    else:
        return redirect(url_for('main.index'))

@bp.route('/events/<genre>')
def jazz(genre):
    jazz = Event.query.filter(Event.genre.jazz).all()
    return render_template('index.html', event=event)

@bp.route('/events/<genre>')
def pop(genre):
    pop = Event.query.filter(Event.genre.pop).all()
    return render_template('index.html', event=event)

@bp.route('/events/<genre>')
def rock(genre):
    rock = Event.query.filter(Event.genre.rock).all()
    return render_template('index.html', event=event)

@bp.route('/events/<genre>')
def kpop(genre):
    kpop = Event.query.filter(Event.genre.kpop).all()
    return render_template('index.html', event=event)

@bp.route('/events/<genre>')
def jpop(genre):
    jpop = Event.query.filter(Event.genre.jpop).all()
    return render_template('index.html', event=event)

@bp.route('/events/<genre>')
def cpop(genre):
    cpop = Event.query.filter(Event.genre.cpop).all()
    return render_template('index.html', event=event)

@bp.route('/events/<genre>')
def other(genre):
    other = Event.query.filter(Event.genre.other).all()
    return render_template('index.html', event=event)

@bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth.login'))

@bp.route('/creation', methods=['GET','POST'])
@login_required
def createEvent():
    createEvent_form = EventForm()
    return render_template(
        'creation.html', current_user=current_user,form=createEvent_form)

@bp.route('/history', methods=['GET','POST'])
@login_required
def history():
    """Logged-in User Dashboard."""
    return render_template(
        'book_history.html',
         current_user=current_user,
    )

@bp.route('/details', methods=['GET','POST'])
@login_required
def event_details():
    """Logged-in User Dashboard."""
    return render_template(
        'event_details.html',
        current_user=current_user
    )

IAB207-project/website/templates/base-fullscreen.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Musics in Malaysia</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style/style.css')}}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Bootstrap Font Icon CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
    />

    <!-- Bootstrap Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>
  
  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-inverse">
        <div class="container-fluid">
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#mynavbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/"
                  >Home
                  <div class="nav-borderline"></div
                ></a>
              </li>

              <li role="presentation" class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  >Events</a
                >
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="/creation"
                      >Events List</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="/creation"
                      >Create Events</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="/creation"
                      >Update Events</a
                    >
                  </li>
                </ul>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="/history">Book History</a>
              </li>
            </ul>
          </div>

          <a href="/" class="navbar-brand"
            ><img src="{{ url_for('static',filename='img/logo1.png')}}" alt= "Eventos logo"/>
          </a>

            <a class="nav-link" style="color: white;" href="{{url_for('auth.register')}}">Logout</a>
        </div>
      </nav>
      {% block header %}
      {% endblock %}
    </header>

    {% block content %}
    {% endblock %}
  </body>

  <!-- Footer -->
  <footer class="bg-dark text-white">
    <!-- Copyright -->
    <div class="text-center py-3">
      <div class="m-3">
        <img src="{{ url_for('static',filename='img/logo1.png')}}" alt="Eventos logo" />
      </div>
      © 2022 Copyright:
      <a href="/" style="text-decoration: none" class="fw-bold">
        Eventos</a
      >
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</html>

IAB207-project/website/templates/book_history.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Musics in Malaysia</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/wyn/website/templates/css/style.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Bootstrap Font Icon CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
    />

    <!-- Bootstrap Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#mynavbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>

            <li role="presentation" class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                >Events</a
              >
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="/"
                    >Events List</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="/creation"
                    >Create Events</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="/creation"
                    >Update Events</a
                  >
                </li>
              </ul>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="/history">Book History</a>
            </li>
          </ul>
        </div>

        <a href="/" class="navbar-brand"
          ><img src="/static/img/logo1.png" alt="eventos"
        /></a>
      </div>
    </nav>
  </header> 

  <body>
    <div class="container mt-5 mb-5 p-5 border-top border-bottom">
      <div class="row">
        <h3 class="fw-bold text-uppercase p-2 mx-auto text-center" id="update">
          Booked Events History
        </h3>
        <div class="border-line" style="background-color: darkblue"></div>
      </div>

      <div class="table-responsive">
        <table class="table align-middle text-center">
          <thead class="text-white bg-dark">
            <tr class="text-center">
              <th scope="col" style="width: 10%">#</th>
              <th scope="col" colspan="2" style="width: 50%">Event</th>
              <th scope="col" style="width: 10%">Booking Order ID</th>
              <th scope="col" style="width: 10%">Booked Datetime</th>
              <th scope="col" style="width: 10%">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">1</th>
              <td class="text-center p-3">
                <img
                  src="/static/img/jazzjulian.jpg"
                  alt="jazz julian"
                  class="img-fluid"
                />
              </td>
              <td class="text-primary fw-bold">
                Bobo Kuala Lumpur presents THE JULIAN CHAN JAZZ QUINTET
              </td>
              <td>17625900</td>
              <td>12 APRIL 2022</td>
              <td>Cancelled</td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td class="text-center p-3">
                <img src="/static/img/kljazz.png" alt="jazz julian" class="img-fluid" />
              </td>
              <td class="text-primary fw-bold">
                KL International Jazz & Arts Festival 2019
              </td>
              <td>85217600</td>
              <td>29 September 2019</td>
              <td>Ended</td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td class="text-center p-3">
                <img
                  src="/static/img/unesco.jpeg"
                  alt="jazz julian"
                  class="img-fluid"
                />
              </td>
              <td class="text-primary fw-bold">
                Incubus Live in Kuala Lumpur 2018 Malaysia
              </td>
              <td>85248310</td>
              <td>13 February 2018</td>
              <td>Completed</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </body>
  <!-- Footer -->
  <footer class="bg-dark text-white">
    <!-- Copyright -->
    <div class="text-center py-3">
      <div class="m-3">
        <img src="img/logo1.png" alt="Eventos logo" />
      </div>
      © 2022 Copyright:
      <a href="index.html" style="text-decoration: none" class="fw-bold">
        Eventos</a
      >
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</html>

IAB207-project/website/templates/event_details.html
{% extends 'base-fullscreen.html' %}
<!-- {% import "bootstrap/wtf.html" as wtf %} -->
{% import "bootstrap/form.html" as wtf %}

{% block header %}
  <!-- Detail -->
  <div class="container">
    <h1 class="fw-bold px-5 text-center" style="margin: 2rem 10%">
      {{event.name}}
    </h1>
    <div class="border-line"></div>
  </div>

  <div class="container mt-3 p-5 shadow mb-5 bg-white rounded-3">
    <div class="row align-items-center p-3 text-center">
      <div class="col-6 col-md-6 p-3">
        <!-- <picture> -->
        <!-- <img
          src="img/futuremusic.png"
          alt=""
          sizes="(max-width: 1700px) 400px, 300px"
          srcset="
            img/resize/jazzjulian_50.jpg 512w,
            img/resize/jazzjulian_80.jpg 819w,
            img/resize/jazzjulian_30.jpg 307w
          "
        /> -->
        <img
          src="{{ event.image }}"
          alt="test"
          class="rounded"
          sizes="(max-width: 1024px) 400px, 700px"
        />
        <!-- 80-492, 50-308, 30-185 -->
        <!-- old, 50-512, 80-819, 30-307 -->
        <!-- </picture> -->
      </div>

      <div class="col-12 col-md-6 p-3">
        <p class="text-left" style="font-size: large; text-align:end;">
          <span
            class="font-italic text-primary fw-bold"
            style="font-style: italic"
          >
          {{event.artists}} <br />
          </span>
          {{event.description}} <br />
          <span class="text-primary fw-bold"> This event is scheduled for the {{event.date}}</span>
        </p>
      </div>
    </div>

    <div class="row align-items-center p-3 text-center">
      <div class="col-6 col-md-6 p-3">
        <!-- <picture> -->
        <!-- <img
          src="img/futuremusic.png"
          alt=""
          sizes="(max-width: 1700px) 400px, 300px"
          srcset="
            img/resize/jazzjulian_50.jpg 512w,
            img/resize/jazzjulian_80.jpg 819w,
            img/resize/jazzjulian_30.jpg 307w
          "
        /> -->
        <img
          src="img/justinticket.png"
          alt=""
          class="rounded"
          sizes="(max-width: 1024px) 300px, 500px"
          srcset="
            img/resize/justinticket_512.png 512w,
            img/resize/justinticket_800.png 800w,
            img/resize/justinticket_307.png 307w
          "
        />
        <!-- 80-492, 50-308, 30-185 -->
        <!-- old, 50-512, 80-819, 30-307 -->
        <!-- </picture> -->
      </div>

      <div class="col-12 col-md-6 p-3">
        <h3
          class="bg-danger bg-custom bg-gradient text-center text-white p-3 m-3 rounded-3"
        >
          <span class="text-uppercase">{{event.date}}</span> 
          <br />
          {{event.time}}
        </h3>

        <div class="row">
          <div class="col-12 col-md-6 fw-bold p-5" style="font-size: larger">
            <span class="text-danger">Location(s): </span> <br />
            {{event.location}}
          </div>

          <div class="col-12 col-md-6 fw-bold p-5" style="font-size: larger">
            <span class="text-danger">Organizer(s): </span> <br />
            <p class="text-jus">
              {{event.organiser}}
              <br />
              Contact Person: {{event.organiser}}
              <br />
              Email:
              <a href="mailto:seanghazi@gmail.com">{{event.email}}</a>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="row align-items-center px-5 m-4">
      <div class="fw-bold container">
        <div class="text-danger text-center p-1">
          <h5>
            <i class="bi bi-exclamation-triangle" style="color: #dc3545"></i>
            Important Information
          </h5>
        </div>
        <div>
          <ol class="list-group list-group-numbered">
            <li class="list-group-item list-group-item-danger">
              Limited to 4 tickets per customer
            </li>
            <li class="list-group-item list-group-item-danger">
              Children under the age of 14 must be accompanied by a
              parent/legal guardian at all times and have purchased a valid
              ticket
            </li>
            <li class="list-group-item list-group-item-danger">
              For successful transactions, only booking confirmation will be
              delivered via email to the purchaser. E-ticket delivery will be
              supressed until a date closer to the event
            </li>
            <li class="list-group-item list-group-item-danger">
              Available to fully vaccinated individuals who have, by the event
              date: <br />
              <p style="font-style: italic; font-size: small">
                Completed 14 days after 2 doses of vaccine (Pfizer, Astra
                Zeneca, Sinovac), or 28 days after 1 dose of vaccine (Johnson
                & Johnson, CanSino)
              </p>
            </li>
            <li class="list-group-item list-group-item-danger">
              PET (Pre-Event Testing) may be required for this event. All
              ticket holders may be required to upload Covid-19 test results
              24 hrs prior to the event date to receive event e-tickets.
            </li>
            <li class="list-group-item list-group-item-danger">
              All other ticketing, venue & event entry terms & conditions
              apply.
            </li>
          </ol>
        </div>
      </div>
    </div>

    <!-- Button trigger booking event modal -->
    <div class="align-item-center text-center mt-3">
      <button
        class="btn btn-success mx-5 px-5 py-3 rounded-3"
        type="button"
        data-bs-toggle="modal"
        data-bs-target="#eventmodal"
      >
        Register Now !
      </button>
    </div>
    <!-- Button trigger booking event modal -->

    <!-- Book Event Modal -->
    <div
      class="modal fade"
      id="eventmodal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="eventModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="eventModalLabel">Register</h5>
            <button
              type="button"
              class="close rounded"
              data-bs-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <form action="#">
              <div class="form-outline">
                <label class="form-label" for="typeNumber">Quantity</label>
                <input type="number" id="quantity" class="form-control" />
              </div>
            </form>
          </div>

          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-danger rounded-3"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <button
              type="button"
              class="btn btn-success rounded-3"
              data-bs-dismiss="modal"
            >
              Submit
            </button>
          </div>
        </div>
      </div>
    </div>
    <!-- Book Event Modal -->
  </div>
  <!-- Detail -->
{% endblock %}
  <!-- Comments -->
{% block title %} Comments {% endblock %}

{% block content %} 
  <!-- Form Comment -->
  <div class="container mt-5 mb-5 pt-5 border-top border-bottom">
    <div class="row">
      <h3 class="fw-bold text-uppercase p-3 mx-auto text-center">
        Please let us know your thoughts! Comment below :)
      </h3>
    </div>
    <!-- {{wtf.quick_form(form,"/event/{0}".format(event.id))}} -->
    {{wtf.render_form(form,"/event/{0}".format(event.id))}} 
    {% for comment in event.comments %}
    <form class="p-5 mx-5">
      <div class="form-group row my-3">
        <label
          for="username"
          class="col-sm-2 col-form-label"
          style="letter-spacing: 1px"
          >{{comment.user.name}}</label
        >
      </div>
      <div class="form-group row my-3">
        <label
          for="inputComment"
          class="col-sm-2 col-form-label"
          style="letter-spacing: 1px"
          >{{comment.text}}</label
        >
      </div>
    </form>
    {% endfor %}
  </div>
  <!-- Form Comment -->
{% endblock %}

IAB207-project/website/templates/index.html
{% extends 'base-fullscreen.html' %}
{% block header %}
  <!-- Background image -->
  <div
    class="bg-image justify-content-center align-items-center"
    style="background-image: url(/static/img/musicevent.jpg); height: 100vh"
  >
    <div
      class="mask"
      style="background-color: rgba(0, 0, 0, 0.8); height: 100vh"
    >
      <div
        class="container d-flex justify-content-center align-items-center h-100 text-center"
      >
        <div class="text-white">
          <h1 class="mb-5 mt-5"><img src="/static/img/logo1.png" alt="" /></h1>
          <h4 class="mb-4">
            Eventos is all about music events around Malaysia!
          </h4>
          <h4 class="mb-4">
            Click the button below to view more events around Malaysia!
          </h4>

          <div class="mb-4">
            <a
              class="btn btn-info btn-lg m-2"
              href="#musicevents"
              role="button"
              rel="nofollow"
              style="color: white"
              ><i class="bi-arrow-down-short"></i>More Events<i
                class="bi-arrow-down-short"
              ></i
            ></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->

  <!-- Music Type -->
  <div class="mt-5 text-center">
    <h1 id="musicevents">
      <br />
      Genre of <strong class="text-info">Music Events</strong> in Malaysia!
    </h1>

    <div class="container">
      <h5 class="m-5 p-5">
        Music can be divided into genres in varying ways, such as popular
        music and art music, or religious music and secular music. The
        artistic nature of music means that these classifications are often
        subjective and controversial, and some genres may overlap. In Eventos,
        we most focus on
        <a href="#jazz" class="music">Jazz Music</a>,
        <a href="#pop" class="music">Pop Music</a> and
        <a href="#rock" class="music">Rock Music</a>!
        <br />
        There will have more different genres of music in the future! Please
        stay tuned for future updates!
      </h5>
    </div>

    <br />
  </div>
  <!-- Music Type -->
  <hr />

  <hr class="mt-5" />
  <!-- All Events -->
  <div class="mt-5 text-center">
    <h2 class="mt-5">All Music Events in Malaysia</h2>
    <div class="border-line" style="color: #0980d0"></div>
  </div>

  <div class="container">
    <div class="row">
      <!-- Filter Events -->
      <div id="filter" class="col-12 col-md-7 p-3">
        <i class="bi bi-filter"></i>
        <form action="/events/all" method="post" style="display:inline-block">
          <button class="btn btn-primary filter-button" name="showall" type="submit">All</button>
        </form>
        <form action="/events/jazz" method="post" style="display:inline-block">
          <button class="btn btn-outline-primary filter-button" name="jazz" type="submit">Jazz</button>
        </form>
        <form action="/events/pop" method="post" style="display:inline-block">
          <button class="btn btn-outline-primary filter-button" name="pop" type="submit">Pop</button>
        </form>
        <form action="/events/rock" method="post" style="display:inline-block">
          <button class="btn btn-outline-primary filter-button" name="rock" type="submit">Rock</button>
        </form>
        <form action="/events/jpop" method="post" style="display:inline-block">
          <button class="btn btn-outline-primary filter-button" name="jpop" type="submit">J-Pop</button>
        </form>
        <form action="/events/kpop" method="post" style="display:inline-block">
          <button class="btn btn-outline-primary filter-button" name="kpop" type="submit">K-Pop</button>
        </form>
        <form action="/events/cpop" method="post" style="display:inline-block">
          <button class="btn btn-outline-primary filter-button" name="cpop" type="submit">C-Pop</button>
        </form>
        <form action="/events/other" method="post" style="display:inline-block">
          <button class="btn btn-outline-primary filter-button" name="others" type="submit">Others</button>
        </form>
      </div>
      <!-- Filter Events -->

      <!-- Search -->
      <div class="col-12 col-md-5 p-3">
        <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}" >
          <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm">
          <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
        </form>
      </div>
      <!-- Search -->
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for event in event %}
      
      <div class="col mb-4">
        <div class="card">
          <div class="backgroundEffect">
            <h5 class="card-title">{{event.name}}</h5>
            <img src={{event.image}} class="card-img-top" alt="...">
            <div class="card-body">
              <br />
              <span class="text-primary fw-bold">{{event.location}} on {{event.date}} at {{event.time}} </span>
              <br />
              <span class="text-primary fw-bold">{{event.description}}</span>
              <br />
              <p class="card-text">{{event.status}}</p>
              <a button type="button" class="btn btn-info" href="{{url_for('event.show', id=event.id)}}">Read More</a> 
            </div>
          </div>
        </div>
      </div>
    
    {% endfor %}
  </div>


{% endblock %}


IAB207-project/website/templates/user.html
{% extends "base-fullscreen.html" %}
<!-- {% import "bootstrap/wtf.html" as wtf %} -->
{% import "bootstrap/form.html" as wtf %}
{% block content %}
<div class="page-header">
    <h4>{{heading}}</h4>
</div>


<div class="container-fluid">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in get_flashed_messages() %}
    <div class ="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
        {{message}}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}


</div>

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6">
<!-- {{wtf.quick_form(form)}} -->
{{wtf.render_form(form)}}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endif %}

{% endblock %}